CREATE TABLE assets (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE asset_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    asset_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO assets (user_id, name) VALUES
    (1, "USD"),
    (2, "FXIT"),
    (3, "BTC");